#!/usr/bin/env python3
"""Generate ACTION and GOTO parse-table matrices from bison .output file."""

from __future__ import annotations

import argparse
import csv
import re
from collections import defaultdict
from pathlib import Path


STATE_RE = re.compile(r"^[Ss]tate\s+(\d+)\s*$")
SHIFT_RE = re.compile(r"^\s*(\S+)\s+shift, and go to state\s+(\d+)")
REDUCE_RE = re.compile(r"^\s*(\S+)\s+\[?reduce using rule\s+(\d+)")
ACCEPT_RE = re.compile(r"^\s*(\S+)\s+accept")
GOTO_RE = re.compile(r"^\s*([a-z_][a-zA-Z0-9_]*)\s+go to state\s+(\d+)")


def parse_output(output_path: Path):
    action = defaultdict(dict)
    goto = defaultdict(dict)
    action_symbols = set()
    goto_symbols = set()

    current_state = None

    for raw_line in output_path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw_line.rstrip("\n")

        state_match = STATE_RE.match(line)
        if state_match:
            current_state = int(state_match.group(1))
            continue

        if current_state is None:
            continue

        shift_match = SHIFT_RE.match(line)
        if shift_match:
            symbol, next_state = shift_match.groups()
            action_symbols.add(symbol)
            prev = action[current_state].get(symbol)
            entry = f"s{next_state}"
            action[current_state][symbol] = merge_entry(prev, entry)
            continue

        reduce_match = REDUCE_RE.match(line)
        if reduce_match:
            symbol, rule_no = reduce_match.groups()
            action_symbols.add(symbol)
            prev = action[current_state].get(symbol)
            entry = f"r{rule_no}"
            action[current_state][symbol] = merge_entry(prev, entry)
            continue

        accept_match = ACCEPT_RE.match(line)
        if accept_match:
            symbol = accept_match.group(1)
            action_symbols.add(symbol)
            prev = action[current_state].get(symbol)
            action[current_state][symbol] = merge_entry(prev, "acc")
            continue

        goto_match = GOTO_RE.match(line)
        if goto_match:
            nonterminal, next_state = goto_match.groups()
            goto_symbols.add(nonterminal)
            goto[current_state][nonterminal] = next_state

    states = sorted(set(action.keys()) | set(goto.keys()))
    return states, sorted(action_symbols), sorted(goto_symbols), action, goto


def merge_entry(previous: str | None, new_entry: str) -> str:
    if previous is None:
        return new_entry
    if new_entry in previous.split("/"):
        return previous
    return f"{previous}/{new_entry}"


def write_csv(path: Path, states, symbols, table):
    with path.open("w", newline="", encoding="utf-8") as fp:
        writer = csv.writer(fp)
        writer.writerow(["state", *symbols])
        for state in states:
            row = [state]
            row.extend(table[state].get(symbol, "") for symbol in symbols)
            writer.writerow(row)


def write_summary(path: Path, states, action_symbols, goto_symbols):
    summary = [
        "# Parsing Table Summary",
        "",
        f"- States: {len(states)}",
        f"- ACTION columns: {len(action_symbols)}",
        f"- GOTO columns: {len(goto_symbols)}",
        "",
        "Generated by tools/parse_table_matrix.py",
    ]
    path.write_text("\n".join(summary) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build parse table matrices from bison output")
    parser.add_argument("--input", default="yapl.output", help="Path to bison .output file")
    parser.add_argument(
        "--out-dir",
        default="a3_artifacts",
        help="Directory where action_table.csv and goto_table.csv are written",
    )
    args = parser.parse_args()

    output_path = Path(args.input)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    states, action_symbols, goto_symbols, action, goto = parse_output(output_path)

    write_csv(out_dir / "action_table.csv", states, action_symbols, action)
    write_csv(out_dir / "goto_table.csv", states, goto_symbols, goto)
    write_summary(out_dir / "parsing_table_summary.md", states, action_symbols, goto_symbols)

    print(f"Wrote {out_dir / 'action_table.csv'}")
    print(f"Wrote {out_dir / 'goto_table.csv'}")
    print(f"Wrote {out_dir / 'parsing_table_summary.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
